apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knicks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chirag-baghra/AiOPS-Project-knicks-store.git'
    targetRevision: main
    path: gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: knicks
  syncPolicy: {}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
